BEGIN;

-- Opening variants v1 (CHN, USA, EU)
INSERT INTO opening_variants (id, role_id, opening_text, initial_stances, conversation_interests)
VALUES
(
  '0f0c6a46-8d5a-4edb-8e07-3e2d1e4d2a10',
  'CHN',
  'China approaches this working group with seriousness and discipline. Mercury is a substance that demands respect, but respect does not require exaggeration. The question before us is not whether mercury can cause harm at high exposure. The question is whether the current scientific record justifies binding global obligations that would constrain national development pathways, particularly for countries still lifting hundreds of millions of people out of poverty.\n\nThe International Mercury Assessment confirms that mercury exists naturally, cycles globally for long periods, and is subject to major uncertainty at every stage, from emissions inventories to ecosystem response. It also shows that historic emissions and re-emissions from industrialized regions continue to circulate globally. These facts matter. They mean responsibility cannot be assigned selectively, and they mean policy must be grounded in evidence, not fear.\n\nChina’s first priority is sovereignty. Decisions about energy systems, industrial structure, and emissions controls must remain primarily national decisions. Countries have different stages of development, different capacities, and different exposure profiles. A single, binding framework imposed prematurely would ignore these realities and risk serious economic harm with unclear environmental benefit.\n\nOur second priority is credibility. If this process is to move forward, it must be based on complete and balanced science. Current data gaps are substantial, especially in emissions inventories and in understanding how ecosystems respond to reductions over time. We will not support commitments that rest on assumptions rather than demonstrated outcomes.\n\nChina’s red line is clear. We will not accept mandatory emissions targets or legally binding controls on atmospheric mercury at this stage. The evidence does not justify it, and the costs would fall unfairly on developing economies.\n\nAt the same time, China is prepared to engage constructively. We are open to enhanced voluntary measures, information sharing, and coordinated research. We see flexibility in discussing intentional uses of mercury in products and processes where safe, affordable alternatives already exist, provided that these discussions respect national circumstances and do not restrict legitimate trade.\n\nChina asks other parties, particularly developed countries, to acknowledge their historic contributions and to focus this working group on realistic next steps: improving data quality, supporting technology transfer, and addressing high-risk, localized sources where clear health benefits can be demonstrated. Progress will come from discipline and fairness, not from rushing toward conclusions that science does not yet support.',
  '{"summary":{"top_priorities":["national sovereignty over emissions and industrial policy","evidence-based and gradual international action"],"red_lines":["mandatory global emissions targets","legally binding atmospheric mercury controls at this stage"],"flexibilities":["voluntary measures","discussion of products and processes with viable alternatives","expanded scientific cooperation and data collection"]},"by_issue_id":{"ISSUE_1":{"preferred":"1.2","firmness":0.85},"ISSUE_2":{"preferred":"2.2","firmness":0.90},"ISSUE_3":{"preferred":"3.2","firmness":0.55},"ISSUE_4":{"preferred":"4.2","firmness":0.60}}}'::jsonb,
  '{"targets":["EU","USA","CAN","CHAIR"],"topics":[{"topic":"historic emissions and responsibility","intent":"probe","details":"Press developed countries to acknowledge re-emissions from past industrial activity."},{"topic":"data gaps and inventories","intent":"ask","details":"Call for expanded monitoring and research before binding commitments."},{"topic":"voluntary versus binding action","intent":"warn","details":"Signal resistance to premature legal obligations."}]}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  role_id = EXCLUDED.role_id,
  opening_text = EXCLUDED.opening_text,
  initial_stances = EXCLUDED.initial_stances,
  conversation_interests = EXCLUDED.conversation_interests;

INSERT INTO opening_variants (id, role_id, opening_text, initial_stances, conversation_interests)
VALUES
(
  'dcb21c1f-3455-4f9f-b9ad-6e042baf2a5d',
  'USA',
  'The United States approaches this working group with confidence in both the scientific process and the value of international cooperation. Mercury presents a complex challenge, but complexity is not an excuse for inaction. The scientific record before us demonstrates that mercury can travel long distances, bioaccumulate in ecosystems, and pose risks to human health, particularly through dietary exposure.\n\nThe International Mercury Assessment makes clear that while uncertainty exists, the overall direction of the evidence is consistent. Anthropogenic mercury emissions have increased global cycling well beyond natural background levels, and atmospheric transport links the actions of one country to the impacts experienced by others. For the United States, this finding is central. When pollution crosses borders, cooperation becomes a necessity rather than a choice.\n\nOur primary priority is effective global action that delivers real environmental and health benefits. That means focusing on sources that matter most, especially atmospheric emissions from large-scale industrial activity. It also means designing commitments that are transparent, measurable, and compatible with national implementation.\n\nThe United States is firm in its view that voluntary efforts alone are unlikely to achieve meaningful global reductions. While voluntary measures have value, they are not sufficient given the scale of emissions and the persistence of mercury in the environment. For this reason, we support moving toward a structured international framework that includes clear expectations for participation.\n\nAt the same time, the United States recognizes the importance of flexibility. Countries differ in capacity, and obligations should reflect those differences. We are prepared to support phased approaches, technical cooperation, and assistance to help developing countries meet agreed objectives, provided that commitments are credible and verifiable.\n\nWe also see strong opportunities for progress on mercury use in products and industrial processes, where alternatives are already available or emerging. Reducing intentional uses can deliver faster and more certain benefits, and these measures should be an integral part of any future agreement.\n\nThe United States asks its partners to engage seriously with the evidence and to move beyond debating whether action is needed. The more productive question is how to act in a way that is fair, effective, and grounded in science. We stand ready to work with all parties to build that path forward.',
  '{"summary":{"top_priorities":["effective global action on mercury","reductions in major anthropogenic emissions"],"red_lines":["exclusive reliance on voluntary measures","agreements without transparency or accountability"],"flexibilities":["phased implementation","technical and financial assistance","differentiated responsibilities"]},"by_issue_id":{"ISSUE_1":{"preferred":"1.1","firmness":0.85},"ISSUE_2":{"preferred":"2.1","firmness":0.80},"ISSUE_3":{"preferred":"3.2","firmness":0.65},"ISSUE_4":{"preferred":"4.1","firmness":0.70}}}'::jsonb,
  '{"targets":["EU","CAN","CHN","CHAIR"],"topics":[{"topic":"binding versus voluntary action","intent":"offer","details":"Promote a structured international framework with flexibility in implementation."},{"topic":"atmospheric emissions","intent":"ask","details":"Push for inclusion of major anthropogenic sources with reporting and accountability."},{"topic":"support for developing countries","intent":"offer","details":"Discuss technical and financial assistance tied to credible commitments."}]}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  role_id = EXCLUDED.role_id,
  opening_text = EXCLUDED.opening_text,
  initial_stances = EXCLUDED.initial_stances,
  conversation_interests = EXCLUDED.conversation_interests;

INSERT INTO opening_variants (id, role_id, opening_text, initial_stances, conversation_interests)
VALUES
(
  '4b28a4f1-6f52-4c51-9c6a-5a2ef3bc7a23',
  'EU',
  'The European Union approaches this working group with a clear view of both the science and the responsibility it implies. Mercury pollution is not confined by borders. Its ability to travel long distances, persist in the environment, and accumulate in food webs makes it a shared challenge that no country can address alone.\n\nThe International Mercury Assessment demonstrates that human activity has significantly altered the global mercury cycle. While uncertainties remain, the direction of the evidence is consistent. Mercury exposure poses risks to human health, particularly for vulnerable populations, and to ecosystems already under multiple pressures. Waiting for perfect certainty would mean accepting continued harm despite credible warnings.\n\nFor the European Union, precaution is not a slogan. It is a policy principle grounded in experience. History shows that delayed action on persistent pollutants often leads to higher environmental and economic costs in the long term. The evidence before us is sufficient to justify moving beyond voluntary cooperation toward a more structured international response.\n\nThe EU’s primary priority is the reduction of anthropogenic mercury emissions, especially atmospheric releases from major industrial sources. These emissions contribute directly to global deposition and undermine the efforts of countries that have already invested in controls. A credible international framework must address this imbalance.\n\nAt the same time, the European Union recognizes that responsibilities must reflect capacities. We support differentiated implementation, phased commitments, and targeted assistance for developing countries. Equity strengthens agreements when it is paired with clear expectations and transparency.\n\nThe EU also sees immediate opportunities to reduce mercury use in products and industrial processes. Where alternatives exist, continued reliance on mercury is difficult to justify. Addressing intentional uses can deliver measurable benefits and build confidence in broader cooperation.\n\nThe European Union invites all parties to focus on outcomes rather than positions. The task before us is not to debate whether mercury is a problem, but to design a response that is credible, fair, and effective. We are prepared to work with all partners to advance that goal.',
  '{"summary":{"top_priorities":["precautionary global action on mercury","reduction of major anthropogenic emissions"],"red_lines":["continued reliance on voluntary measures alone","exclusion of major atmospheric sources from scope"],"flexibilities":["phased implementation","differentiated responsibilities","financial and technical assistance"]},"by_issue_id":{"ISSUE_1":{"preferred":"1.1","firmness":0.90},"ISSUE_2":{"preferred":"2.1","firmness":0.85},"ISSUE_3":{"preferred":"3.2","firmness":0.75},"ISSUE_4":{"preferred":"4.1","firmness":0.70}}}'::jsonb,
  '{"targets":["USA","CAN","CHN","CHAIR"],"topics":[{"topic":"precaution and scientific sufficiency","intent":"offer","details":"Frame action as justified despite uncertainty, based on accumulated evidence."},{"topic":"atmospheric emissions reductions","intent":"ask","details":"Seek inclusion of major industrial sources within a binding framework."},{"topic":"equity and implementation support","intent":"offer","details":"Promote assistance mechanisms tied to clear commitments."}]}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  role_id = EXCLUDED.role_id,
  opening_text = EXCLUDED.opening_text,
  initial_stances = EXCLUDED.initial_stances,
  conversation_interests = EXCLUDED.conversation_interests;

COMMIT;
